name: wbc-classifier
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - pillow
  - tqdm
  - pyarrow          
  - jupyter
  - pytorch
  - torchvision
  - pip
  - pip:
      - torchstain   
